"""Training-data utilities for SEDAR Retrieval v3."""

from .synthetic_queries import (
    DEFAULT_PROMPT_VERSION,
    GENERATOR_SYSTEM_PROMPT,
    QUERY_TYPES,
    SyntheticBuildReport,
    SyntheticGenerationConfig,
    SyntheticGenerationErrorRecord,
    SyntheticQueryRecord,
    SyntheticRejectionRecord,
    TemplateQueryGenerator,
    TransformersQueryGenerator,
    assign_document_splits,
    build_generator_prompt,
    build_synthetic_records,
    load_synthetic_records,
    synthetic_prompt_sha256,
    validate_document_isolation,
    write_generation_errors,
    write_synthetic_records,
    write_synthetic_rejections,
)

__all__ = [
    "DEFAULT_PROMPT_VERSION",
    "GENERATOR_SYSTEM_PROMPT",
    "QUERY_TYPES",
    "SyntheticBuildReport",
    "SyntheticGenerationConfig",
    "SyntheticGenerationErrorRecord",
    "SyntheticRejectionRecord",
    "SyntheticQueryRecord",
    "TemplateQueryGenerator",
    "TransformersQueryGenerator",
    "assign_document_splits",
    "build_generator_prompt",
    "build_synthetic_records",
    "load_synthetic_records",
    "synthetic_prompt_sha256",
    "validate_document_isolation",
    "write_generation_errors",
    "write_synthetic_records",
    "write_synthetic_rejections",
]
