"""Retrieval subpackage for SEDAR Retrieval v3."""

from .bm25_passages import (
    build_passage_bm25_index,
    corpus_fingerprint,
    hits_to_ranked_ids,
    load_passages_and_build,
    search_passages,
    write_index_manifest,
)
from .dense import (
    DEFAULT_DENSE_MODEL,
    DEFAULT_E5_PASSAGE_PREFIX,
    DEFAULT_E5_QUERY_PREFIX,
    DEFAULT_INPUT_FORMAT,
    DEFAULT_QUERY_INSTRUCTION,
    DENSE_CACHE_SCHEMA_VERSION,
    DENSE_INDEX_SCHEMA_VERSION,
    DENSE_INDEX_TYPE,
    DENSE_INPUT_FORMATS,
    DenseDependencyError,
    DenseIndexError,
    DenseIndexManifest,
    DenseSearchHit,
    LoadedDenseIndex,
    SentenceTransformerEncoder,
    build_dense_index_scaffold,
    dense_cache_fingerprint,
    dense_manifest_to_dict,
    format_instruct_query,
    format_passage_text,
    format_query_text,
    length_bucket_order,
    load_dense_index,
    normalize_embedding_matrix,
    require_dense_encode,
    search_dense_index,
    validate_embedding_matrix,
    write_passage_metadata,
)
from .fusion import FusedCandidate, RetrieverHit, reciprocal_rank_fusion
from .passage_adapter import load_passages_jsonl, passage_to_legal_chunk

__all__ = [
    "DEFAULT_DENSE_MODEL",
    "DEFAULT_E5_PASSAGE_PREFIX",
    "DEFAULT_E5_QUERY_PREFIX",
    "DEFAULT_INPUT_FORMAT",
    "DEFAULT_QUERY_INSTRUCTION",
    "DENSE_CACHE_SCHEMA_VERSION",
    "DENSE_INPUT_FORMATS",
    "DENSE_INDEX_SCHEMA_VERSION",
    "DENSE_INDEX_TYPE",
    "DenseDependencyError",
    "DenseIndexError",
    "DenseIndexManifest",
    "DenseSearchHit",
    "FusedCandidate",
    "LoadedDenseIndex",
    "RetrieverHit",
    "SentenceTransformerEncoder",
    "build_dense_index_scaffold",
    "build_passage_bm25_index",
    "corpus_fingerprint",
    "dense_cache_fingerprint",
    "dense_manifest_to_dict",
    "format_passage_text",
    "format_query_text",
    "format_instruct_query",
    "hits_to_ranked_ids",
    "load_passages_and_build",
    "load_dense_index",
    "load_passages_jsonl",
    "length_bucket_order",
    "normalize_embedding_matrix",
    "passage_to_legal_chunk",
    "reciprocal_rank_fusion",
    "require_dense_encode",
    "search_dense_index",
    "search_passages",
    "validate_embedding_matrix",
    "write_index_manifest",
    "write_passage_metadata",
]
