"""Public retrieval helpers."""

from .evidence import (
    DeduplicationDrop,
    DeduplicationError,
    DeduplicationResult,
    EvidencePackingError,
    deduplicate_chunks,
    deduplicate_hits,
    deduplicate_retrieved_chunks,
    normalize_chunk_text,
    pack_evidence,
    pack_retrieved_evidence,
)
from .retrieval.bm25 import retrieve_bm25
from .retrieval.reranker import (
    DEFAULT_RERANKER_BATCH_SIZE,
    DEFAULT_RERANKER_MAX_LENGTH,
    DEFAULT_SEMANTIC_RERANKER_MODEL,
    MockReranker,
    NoOpReranker,
    NoopReranker,
    Reranker,
    RerankerProtocol,
    RerankMetadataValue,
    RerankResult,
    RerankScoreFunction,
    SemanticModelLoader,
    SemanticReranker,
    SemanticRerankerError,
    SemanticRerankerUnavailableError,
    SentenceTransformerReranker,
    create_reranker,
)

__all__ = [
    "DeduplicationDrop",
    "DeduplicationError",
    "DeduplicationResult",
    "EvidencePackingError",
    "deduplicate_chunks",
    "deduplicate_hits",
    "deduplicate_retrieved_chunks",
    "normalize_chunk_text",
    "pack_evidence",
    "pack_retrieved_evidence",
    "retrieve_bm25",
    "DEFAULT_RERANKER_BATCH_SIZE",
    "DEFAULT_RERANKER_MAX_LENGTH",
    "DEFAULT_SEMANTIC_RERANKER_MODEL",
    "MockReranker",
    "NoOpReranker",
    "NoopReranker",
    "RerankResult",
    "RerankMetadataValue",
    "RerankScoreFunction",
    "Reranker",
    "RerankerProtocol",
    "SemanticModelLoader",
    "SemanticReranker",
    "SemanticRerankerError",
    "SemanticRerankerUnavailableError",
    "SentenceTransformerReranker",
    "create_reranker",
]
